# Generated by Django 6.0.3 on 2026-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_date', 'title']},
        ),
        migrations.AddField(
            model_name='blog',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Technology'), (2, 'Business'), (3, 'Lifestyle'), (4, 'News')], default=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='max_page_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='page_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category_type', '-published_date'], name='blog_blog_categor_532e66_idx'),
        ),
    ]
