# Generated by Django 6.0.3 on 2026-04-07 09:57

from django.db import migrations


def populate_status(apps: str, schema_editor: str):
    Blog = apps.get_model('blog', 'Blog')
    
    # Define status mapping by ID
    # ..instead of using CSV file, we are using
    # .. a simple placeholder
    status_map = {
        1: 'published',  # Django Bootcamp
        2: 'draft',      # My Blog
        3: 'draft',      # My Blog
        4: 'published',  # My Super Blog
        5: 'published',  # Second attempt
        6: 'published',  # Fast API Introduction
        7: 'archived',   # Data structures
    }
    
    # Apply mapping
    for blog in Blog.objects.all():
        blog.status = status_map.get(blog.id, 'draft')
        blog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
