# Generated by Django 6.0.3 on 2026-04-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='max_page_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
